# Generated by Django 5.0.7 on 2024-07-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='idioma',
            field=models.CharField(choices=[('ES', 'Español'), ('EN', 'Inglés')], default='ES', max_length=2),
        ),
    ]
