# Generated by Django 5.0.7 on 2024-10-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_libro_descripcion_en_libro_descripcion_es_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(to='books.autor'),
        ),
    ]
