# Generated by Django 5.0.7 on 2024-10-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_libro_autores'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='is_out_of_stock',
            field=models.BooleanField(default=False, verbose_name='Esta fuera de stock'),
        ),
    ]
