# Generated by Django 5.0.7 on 2024-10-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_libro_is_out_of_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='is_out_of_stock',
            field=models.BooleanField(default=False, verbose_name='Está fuera de stock'),
        ),
    ]
